# https://yaml.org/

file: /home/roma/RadioSongs.md
format: markdown # plain or markdown

removeFromFilenames:
  # 16Bit.FM
  - 16Bit.FM I.D.E.A. Channel | 192K | Music for Experienced Ears -
  - 16Bit.FM CAFE Channel | 192K | Music for Relaxation & Conversation -
  - 16Bit.FM ProBeat Channel | 192K | Groove & Intelligent Sound -
